version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: bc
      POSTGRES_USER: bc
      POSTGRES_PASSWORD: bc
    ports:
      - 5432:5432
    volumes:
    - ./pg.sql:/docker-entrypoint-initdb.d/pg.sql

  proxy:
    image: nginx:1.17.3-alpine
    ports:
      - 8090:80
    volumes:
      - ./nginx-config/local.conf:/etc/nginx/conf.d/default.conf
      - ./public/build:/htdocs


